// Local Guide — live, web-sourced challenges for a place the user doesn't know.
// Generated by the Scout Agent; completion is VERIFIED (anti-cheese) by the Verifier.
// Rewards unlock leagues, friendly fixtures, players, and coaching/club staff.
// Sustainability-first by default; user can disable in settings.

export interface Challenge {
  id: string;
  title: string;
  placeId: string;
  difficulty: "easy" | "medium" | "hard";
  sustainable: boolean;
  reward: { kind: "player" | "staff" | "league" | "fixture"; ref: string };
  sources: string[];
}

export async function suggestChallenges(_args: {
  location: string;
  budget?: number;
  sustainableOnly?: boolean;
}): Promise<Challenge[]> {
  throw new Error("not implemented");
}
